apiVersion: v1
kind: Service
metadata:
  name: blogapp-service
spec:
  selector:
    app: blogapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  # type: LoadBalancer
  type: ClusterIP
