apiVersion: v1
kind: Service
metadata:
  name: blogapp-service
spec:
  selector:
    app: blogapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001
  # type: LoadBalancer
  #type: ClusterIP
  type: NodePort
